INSERT INTO DATABASE.CATEGORY (ID, CATEGORY) VALUES (1, 'Food');
INSERT INTO DATABASE.CATEGORY (ID, CATEGORY) VALUES (2, 'Toys');
INSERT INTO DATABASE.CATEGORY (ID, CATEGORY) VALUES (3, 'Tools');
INSERT INTO DATABASE.CATEGORY (ID, CATEGORY) VALUES (4, 'Alcohol');
INSERT INTO DATABASE.CATEGORY (ID, CATEGORY) VALUES (5, 'Drugs');
