INSERT INTO DATABASE.UNIT (ID, UNIT) VALUES (1, 'Kg');
INSERT INTO DATABASE.UNIT (ID, UNIT) VALUES (2, 'Pcs');
INSERT INTO DATABASE.UNIT (ID, UNIT) VALUES (3, 'M');
INSERT INTO DATABASE.UNIT (ID, UNIT) VALUES (4, 'L');
