INSERT INTO DATABASE.TRANSACTION_TYPE (ID, TYPE) VALUES (1, 'Sale');
INSERT INTO DATABASE.TRANSACTION_TYPE (ID, TYPE) VALUES (2, 'Return');
INSERT INTO DATABASE.TRANSACTION_TYPE (ID, TYPE) VALUES (3, 'Rental');
